name: Terraform Apply to New Relic

on:
  push:
    branches:
      - main
    paths:
      - '**.tf'
      - '**.tfvars'


env:
  TF_BACKEND_SAS_TOKEN: ${{ secrets.AZURE_SAS_TOKEN }}
 
      


jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
     run:
      working-directory: demo


    env:
      TF_VAR_newrelic_api_key: ${{ secrets.NEW_RELIC_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init with backend SAS
        run: terraform init -backend-config="sas_token=$TF_BACKEND_SAS_TOKEN"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -lock-timeout=120s

      - name: Terraform Apply
        run: terraform apply -auto-approve -lock-timeout=120s

