name: Terraform Apply to New Relic

on:
  push:
    branches:
      - main
    paths:
      - '**.tf'
      - '**.tfvars'

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: demo

    env:
      TF_VAR_newrelic_api_key: ${{ secrets.NEW_RELIC_API_KEY }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -lock-timeout=30s

      - name: Terraform Plan
        run: terraform plan -lock-timeout=30s

      - name: Terraform Apply
        run: terraform apply -auto-approve -lock-timeout=120s

